<?php
/**
 * Created by PhpStorm.
 * User: jief2
 * Date: 2018/7/1
 * Time: 1:29
 */

namespace App\Model;

use Phalcon\Mvc\Model;

class ModelBase extends Model
{
    protected $prefix = '';
    protected $tableName = '';

    public function initialize()
    {
        if (!empty($this->tableName))
            $this->setSource($this->prefix . $this->tableName);
    }

    public function getSource()
    {
        if (empty($this->tableName)) {
            return $this->prefix . parent::getSource();
        }
        return parent::getSource();
    }

    /**
     * 尝试调用 未知静态方法的时候 先尝试调用 父级方法，如果抛出异常，调用 query 之后 的方法
     * @param $method
     * @param $arguments
     * @return mixed
     */
    public static function __callStatic($method, $arguments)
    {
        try{
            return parent::__callStatic($method, $arguments); // TODO: Change the autogenerated stub
        }catch (\Error | \Exception $error){
            return static::query() -> $method(...$arguments);
        }
    }
}